- name: Install PostgreSQL 17 client on AL2023
  hosts: api
  become: true

  tasks:
    - name: Install PostgreSQL 17 client
      dnf:
        name: postgresql17
        state: present
    
    - name: Check postgresql 17 client version
      command: psql -V